name: Deploy to Vercel

on:
  push:
    branches:
      - nextjs-homepage-redesign

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: npx vercel --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: prj_TXm3O5Rh3schqet5RhILENFsM59I
          VERCEL_ORG_ID: team_bBOInZZ1CFUwJUXNWoQZ28IL
